// ─────────────────────────────────────────────────────────────
// OpenQASM 2.0 + Qiskit Python Exporter
// ─────────────────────────────────────────────────────────────

import type { GateSequence, QuantumGate } from './polyXMapper';


function gateToQASM(gate: QuantumGate): string {
  switch (gate.type) {
    case 'X':
      return `x q[${gate.target}];`;
    case 'CX':
      return `cx q[${gate.controls![0]}], q[${gate.target}];`;
    case 'CCX':
      return `ccx q[${gate.controls![0]}], q[${gate.controls![1]}], q[${gate.target}];`;
    default:
      return `// unsupported gate ${gate.type}`;
  }
}

export function exportQASM(seq: GateSequence): string {
  const lines: string[] = [
    '// Generated by Poly-X Quantum Logic Converter',
    `// Qubits: ${seq.qubitLabels.join(', ')}`,
    '',
    'OPENQASM 2.0;',
    'include "qelib1.inc";',
    '',
    `qreg q[${seq.numQubits}];`,
    `creg c[${seq.numQubits}];`,
    '',
    '// Quantum circuit',
  ];

  seq.gates.forEach(g => {
    lines.push(`${gateToQASM(g)}  // ${g.booleanOrigin}`);
  });

  lines.push('');
  // Measurement
  for (let i = 0; i < seq.numQubits; i++) {
    lines.push(`measure q[${i}] -> c[${i}];`);
  }

  return lines.join('\n');
}

export function exportQiskit(seq: GateSequence): string {
  const lines: string[] = [
    '# Generated by Poly-X Quantum Logic Converter',
    'from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister',
    'from qiskit import transpile',
    'from qiskit_aer import AerSimulator',
    '',
    `# Qubits: ${seq.qubitLabels.join(', ')}`,
    `qr = QuantumRegister(${seq.numQubits}, 'q')`,
    `cr = ClassicalRegister(${seq.numQubits}, 'c')`,
    'qc = QuantumCircuit(qr, cr)',
    '',
    '# Quantum gates',
  ];

  seq.gates.forEach(g => {
    switch (g.type) {
      case 'X':
        lines.push(`qc.x(qr[${g.target}])  # ${g.booleanOrigin}`);
        break;
      case 'CX':
        lines.push(`qc.cx(qr[${g.controls![0]}], qr[${g.target}])  # ${g.booleanOrigin}`);
        break;
      case 'CCX':
        lines.push(`qc.ccx(qr[${g.controls![0]}], qr[${g.controls![1]}], qr[${g.target}])  # ${g.booleanOrigin}`);
        break;
    }
  });

  lines.push('');
  lines.push('# Measurement');
  for (let i = 0; i < seq.numQubits; i++) {
    lines.push(`qc.measure(qr[${i}], cr[${i}])`);
  }

  lines.push('');
  lines.push('# Draw circuit');
  lines.push("print(qc.draw('text'))");
  lines.push('');
  lines.push('# Run simulation');
  lines.push('simulator = AerSimulator()');
  lines.push('compiled = transpile(qc, simulator)');
  lines.push('job = simulator.run(compiled, shots=1024)');
  lines.push('counts = job.result().get_counts()');
  lines.push('print("Counts:", counts)');

  return lines.join('\n');
}

export function exportJSON(seq: GateSequence, expression: string): string {
  return JSON.stringify({
    expression,
    qubits: seq.qubitLabels,
    numQubits: seq.numQubits,
    gates: seq.gates.map(g => ({
      id: g.id,
      type: g.type,
      target: g.target,
      controls: g.controls,
      label: g.label,
      booleanOrigin: g.booleanOrigin,
      description: g.description,
    })),
  }, null, 2);
}
